[technote]
id = "SQR-107"
series_id = "SQR"
canonical_url = "https://sqr-107.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-107"
github_default_branch = "main"
date_created = 2025-10-09T21:25:40Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Stelios"
name.family = "Voutsinas"
internal_id = "voutsinass"
orcid = "https://orcid.org/0009-0003-4290-2942"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "Tucson"
